-- CREATE DATABASE IF NOT AI_DB;
USE AI_DB;

-- CREATE TABLE sessions(id INT AUTO_INCREMENT PRIMARY KEY, session_name VARCHAR(200), created_at 	TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

-- CREATE TABLE messages(id INT AUTO_INCREMENT PRIMARY KEY, session_id INT, role TEXT, content VARCHAR(1000), 
-- created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk__sessions FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE);
SELECT * FROM sessions;